(source gnu)
(source melpa)
;;(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "auto-install")
(depends-on "rainbow-delimiters")

;; Coding
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "auto-complete")

;; Git
(depends-on "magit")
(depends-on "git-gutter-fringe+")
(depends-on "git-modes" :git "https://github.com/magit/git-modes.git")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")

;;; helm
(depends-on "helm")
(depends-on "helm-gtags")
;(depends-on "helm-git-grep")
;(depends-on "helm-ls-git")
;(depends-on "helm-themes")

;; progmodes
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "yaml-mode")

;; PHP
(depends-on "php-mode")
; php-completion
(depends-on "php-completion"
        :git "https://github.com/suzuki/php-completion.git"
        :branch "develop"
        :files ("*.el" "phpcmp-index-of-*"))

;; Python
(depends-on "python-mode")

;; Ruby
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-end")
